port: 1944
ip: 127.0.0.1
server_cert: ""
max_concurrent_downloads: 1
download_directory: "/tmp"
metadata_directory: "/tmp"
log_directory: "/tmp"
log_config_file: ""
# + intelligent ie factor by size, max concurrent downloads
# make it a max fragments per file, and increase the number of fragments by size of target file
# files with no content-length header will be downloaded in one fragment
fragments: 4
min_fragment_size: 1000000
retries: 1
filemode: 0644
buffer_size: 4096
