port: 1944
ip: 127.0.0.1
server_cert: ""
max_concurrent_downloads: 1
# the downloaded file is saved to this directory before moving to final path
download_directory: "/tmp"
# the downloaded file is moved to this directory after download
final_path: "${filename}/${host}/${id}"
metadata_directory: ".metadata"
log_directory: "/var/log"
log_config_file: ""
# + intelligent ie factor by size, max concurrent downloads
# make it a max fragments per file, and increase the number of fragments by size of target file
# files with no content-length header will be downloaded in one fragment
max_fragments: 4
min_fragment_size: 1000000
retries: 1
filemode: 0644
buffer_size: 81920
timeout: 0s
redirects: 5

#
# kafka config
kafka_bootstrap_servers: localhost:9092
kafka_client_id: "download-client-0"
kafka_topic: "download"
kafka_producer_id: "download-producer-0"
# kafka_config: 
#   acks: 1

#
# local storage config
# the path must be accessible i.e. permissions and existing...
# chown user -R /var/local/storage
storage_path: "/var/local/storage"
storage_buffer_mib: 2
storage_cache_mib: 2
storage_compression: none
storage_recovery: true
