port: 8080
ip: 127.0.0.1
server_cert: ""
max_concurrent_downloads: 1
log_directory: "/var/log"
# files with content-length header will be downloaded in fragments
max_conc_fragments: 4
# fragments are this size if the file size is above this size
max_fragment_size: 5000000
# 1 fragment if below this size
min_fragment_size: 1000000
retries: 1
buffer_size: 81920
timeout: 0s
redirects: 5

#
# kafka config
kafka_bootstrap_servers: localhost:9092
kafka_client_id: "download-client-0"
kafka_topic: "download"
kafka_producer_id: "download-producer-0"
kafka_config:
  retries: 3
  "retry.backoff.ms": 1000

#
# local storage config
# the path must be accessible i.e. permissions and existing...
# chown user -R /var/local/storage
storage_path: "/var/local/storage"
storage_buffer_mib: 2
storage_cache_mib: 2
storage_compression: none
storage_recovery: true

#
# the downloaded file is saved to this directory
# remember to chown user -R /var/local/download
download_directory: "/var/local/download"
# final path containing the file and metadata
# filename/id
path_template: "%s/%s"
# ownership
filemode: 0644

#
# prometheus config
prometheus:
  enable: true
  port: 2112
  model: "push"
  path: "/metrics"
